完善

diff --git a/bin/ovpn_init b/bin/ovpn_init
--- a/bin/ovpn_init
+++ b/bin/ovpn_init
@@ -1,9 +1,52 @@
 #!/bin/bash
-set -e
+set -eu
 
-if [ -z "$1" ]; then
-  echo "[ERROR] 请输入服务端名称"
-  exit 1
+source '/usr/local/bin/func.sh'
+
+usage() {
+    echo "usage: $0 [OPTIONS]"
+    echo " -p port"
+    echo " -m PLUGIN_NAME 验证插件，可选项：pam_mysql"
+    echo " -n SERVER_CERT_NAME 服务证书名称"
+    echo " -s SERVER_SUBNET 内网地址，默认：10.8.0.0/24"
+}
+
+OVPN_PORT=1194
+OVPN_SERVER=10.8.0.0/24
+OVPN_PLUGIN=''
+OVPN_SERVER_CERT_NAME='ovpn-server'
+OVPN_SERVER_CONF="${OPENVPN:-}/server/server.conf"
+OVPN_CLIENT_CONF="${OPENVPN:-}/client"
+OVPN_PAM_MYSQL_PATH=''
+while getopts ":n:s:p:" opt; do
+    case $opt in
+        m)
+            OVPN_PLUGIN="$OPTARG"
+            ;;
+        n)
+            OVPN_SERVER_CERT_NAME="$OPTARG"
+            ;;
+        s)
+            OVPN_SERVER="$OPTARG"
+            ;;
+        p)
+            OVPN_PORT="$OPTARG"
+            ;;
+        \?)
+            set +x
+            echo "Invalid option: -$OPTARG" >&2
+            usage
+            exit 1
+            ;;
+    esac
+done
+
+
+
+
+if [ "$OVPN_PLUGIN" = "pam_mysql" ]; then
+  apt-get -y install libpam-mysql
+  OVPN_PAM_MYSQL_PATH=$(find / | grep pam_mysql.so)
 fi
 
 # 初始化
@@ -19,5 +62,77 @@ easyrsa gen-dh
 openvpn --genkey --secret "$EASYRSA_PKI"/ta.key
 
 # 创建服务端证书
-easyrsa build-server-full "$1" nopass
+easyrsa build-server-full "$OVPN_SERVER_CERT_NAME" nopass
 
+# 吊销证书列表
+easyrsa gen-crl
+
+
+[ ! -d "${OPENVPN:-}/ccd" ] && mkdir -p ${OPENVPN:-}/ccd
+[ ! -d "${OPENVPN:-}/server" ] && mkdir -p ${OPENVPN:-}/server
+
+
+
+cat > "$OVPN_SERVER_CONF" <<EOF
+port ${OVPN_PORT}
+proto udp
+dev tun
+ca ${EASYRSA_PKI}/ca.crt
+cert ${EASYRSA_PKI}/issued/${OVPN_SERVER_CERT_NAME}.crt
+key ${EASYRSA_PKI}/private/${OVPN_SERVER_CERT_NAME}.key
+dh ${EASYRSA_PKI}/dh.pem
+server $(get_route $OVPN_SERVER)
+ifconfig-pool-persist ${OPENVPN}/ipp.txt
+# 固定客户端ip，如：/cdd/user1
+# 内容为ifconfig-push 10.9.0.1 10.9.0.2，则固定ip10.9.0.1
+client-config-dir ${OPENVPN}/ccd
+# 客户端互相可以访问
+client-to-client
+# 可以多个终端登录一个账户
+;duplicate-cn
+# 心跳，每10s ping一次，ping不到60s之后认定客户端宕机
+keepalive 10 60
+# tls 加密验证，服务端为0，客户端为1
+tls-auth ${EASYRSA_PKI}/ta.key 0
+cipher AES-256-CBC
+# 压缩
+comp-lzo
+# 最大连接客户端
+max-clients 1000
+# 使用nobody用户运行，更安全
+# user nobody
+# group nobody
+# 禁止openvpn证书自动过期，以便用户保持连接
+reneg-sec 0
+persist-key
+persist-tun
+# 状态日志
+status ${OPENVPN}/openvpn-status.log
+# 日志级别 0-9,等级越高日志内容越详细
+verb 3
+# 当服务器重新启动时，通知客户端，以便它可以自动重新连接。只支持udp协议
+explicit-exit-notify 1
+EOF
+
+if [ -n "$OVPN_PAM_MYSQL_PATH" ];then
+cat >> "$OVPN_SERVER_CONF" <<EOF
+# pam认证插件，后面是/etc/pam.d的文件名
+plugin ${OVPN_PAM_MYSQL_PATH} openvpn
+# 不验证客户端的证书，但是服务端的证书还是需要的
+client-cert-not-required
+# 使用客户提供的UserName作为Common Name
+username-as-common-name
+EOF
+fi
+
+# Preserve config
+if [ -f "$OVPN_ENV" ]; then
+    bak_env=$OVPN_ENV.$(date +%s).bak
+    echo "Backing up $OVPN_ENV -> $bak_env"
+    mv "$OVPN_ENV" "$bak_env"
+fi
+
+# Save the current OVPN_ vars to the ovpn_env.sh file
+(set | grep '^OVPN_') | while read -r var; do
+  echo "declare -x $var"  >> "$OVPN_ENV"
+done
